### ISSUE TITLE
Dynamic list validation errors display at incorrect indices

### ISSUE THREAD

**Issue by alexmunda** [etaque/elm-form#87] opened 2017-04-21 00:45 UTC
Hi etaque,

First off, thanks for all of your work on elm-form. My team and I have found it to be an extremely useful library and we use it all the time in our application.

One thing we have found is that if you have a form with a dynamic list, and that list has a mix of valid and invalid (error) fields, the index of the validation error does not match up with the index of the offending form fields.

In the below example, the second row of fields have the errors.

<img width="860" alt="screen shot 2017-04-20 at 19 12 51" src="https://cloud.githubusercontent.com/assets/4350743/25257945/63b0c11a-2601-11e7-8a40-fea736b3cd91.png">
<img width="379" alt="screen shot 2017-04-20 at 19 29 50" src="https://cloud.githubusercontent.com/assets/4350743/25257950/69e120f2-2601-11e7-8a63-43af92c2ae3e.png">

Any thoughts on this? Is there a work around or some other way that `Validate.list` could use some sort of dictionary that matches the error index to the field list index? Thanks again for all of your work!

**Comment by etaque** [comment] 2017-06-02 14:26
Hi @alexmunda,
Sorry to be late on this, it looks like a bug indeed. Would you mind setting up a minimal reproductible example on [Ellie](https://ellie-app.com)?

**Comment by stephenreddek** [comment] 2017-06-08 14:54
@etaque ,
I'd like to help out with this one if I can! It looks like part of the problem could be that the tree for errors is different than the tree for values. Is there a design decision behind keeping them separate or could I combine them?

**Comment by etaque** [comment] 2017-06-10 20:07
Great @stephenreddek, I think your intuition is good. I don't remember any obvious reason to keep them separate, my feeling is that's a bit over engineered, you can try to combine them.

**Comment by etaque** [comment] 2017-06-20 10:57
Fixed by #92

**Closed as completed by etaque** 2017-06-20 10:57 UTC
Labels: bug, contrib welcome

**Comment by etaque** [comment] 2017-06-20 11:03
And published in 2.1.0
